:PROPERTIES:
:ID:       a3fa1cb5-5610-4fb2-a349-9425580142f0
:END:
#+HUGO_BASE_DIR: ./
#+HUGO_SECTION: emacs
#+options: toc:t

* Using Emacs
:PROPERTIES:
:EXPORT_FILE_NAME: emacs-info
:END:

Emacsを使うときに役に立つと思われる情報を公開していきます

** 私の Emacs 情報源

Emacs はとても歴史が古く、そのうえ今でも活発に開発が続いている稀有なソフトウェアです。
つまり、Emacs の情報を Web で探そうとすると古今のさまざまなものが引っかかります。しかも玉石混淆です。
特に初心者がこれらを選り分けて自分のほしい情報に早く辿り着くのは実はかなりハードルの高いことだと思います。

ここで紹介するのは、私がふだん Emacs の情報源としているものの一部です。
一個人が集めたものなので当然、偏りがあることにご注意ください。
また、英語で情報提供されているものが多い点はご容赦ください。


- [[https://sachachua.com/blog/category/emacs-news/][Emacs news]] \\

  Emacsの熱心なユーザでコミュニティの世話人的存在の [[https://sachachua.com/blog/][Sacha Chua]] さんが毎週配信するEmacs界の注目情報のリストアップ。
  ブログ記事・ソーシャルニュース・開発トピック・新規パッケージなど幅広い領域から愛好者の視点で編纂されていてとても役にたちます。
  多くのEmacsユーザもすすめる情報源です。
  メール配信もやってます。

- [[https://irreal.org/blog/][Irreal]] \\

  Emacs関連のポストが多い毎日投稿されているブログ。
  その多くはEmacs関連の注目したトピックを彼独自の切り口で紹介しおすすめするスタイル。
  長年の経験にもとづいた鋭い考察とMacユーザならではの視点が交じりあい刺激をもらえるブログ。

- [[https://www.masteringemacs.org/][Mastering Emacs]] \\

  実用面においてこれ以上に優れたEmacsの本はないかと思います。
  Emacsの基礎的な話題から最新バージョン(Ver.27)の新機能の解説まで非常に理解しやすく書かれています。

- [[https://www.youtube.com/c/SystemCrafters][System Crafters]] \\

  EmacsやGNU/Guixなどを紹介するYouTubeチャンネル。

- [[https://emacsconf.org/][EmacsConf]]

  年に一度開催されているカンファレンス。
  ここ数年はオンラインでの開催。
